<a href="https://colab.research.google.com/github/khushalsinghshekhawat/khushal/blob/main/task_4(khushal).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Khushal Singh Shekhawat
TASK 4
 
GO_STP_8909

Q1. Import the numpy package under the name np and Print the numpy version and the configuration.

In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


Q2. Create a null vector of size 10.

In [ ]:
m =np.zeros(10)
print("Result",m)

Result [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Q3. Create Simple 1-D array and check type and check data types in array.

In [ ]:
arr = np.array([10,20,30,40,50,60])
print("Type of array", type(arr))
print("Data types in array", arr.dtype)

Type of array <class 'numpy.ndarray'>
Data types in array int64


Q4. How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
dimn = arr.ndim
print("Number of dimensions : ",dimn)
bytesperele = arr.itemsize
print("Bytes per element : ",bytesperele)
bytesused = arr.nbytes
print("Bytes of memory used : ",bytesused)

Number of dimensions :  1
Bytes per element :  8
Bytes of memory used :  48


Q5. Create a null vector of size 10 but the fifth value which is 1.

In [ ]:
vector =np.zeros(10)
vector[4] =1
print("The required vector : ",vector)

The required vector :  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Q6. Create a vector with values ranging from 10 to 49.

In [ ]:
requiredvector = np.arange(10,50)
print("The vector with values ranging from 10 to 49 : \n" ,requiredvector)

The vector with values ranging from 10 to 49 : 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Q7. Reverse a vector (first element becomes last).

In [ ]:
vctr = np.arange(34,43)
print("Original Vector : ",vctr)
revvec = vctr[::-1]
print("Reversed vector : ",revvec)

Original Vector :  [34 35 36 37 38 39 40 41 42]
Reversed vector :  [42 41 40 39 38 37 36 35 34]


Q8. Create a 3x3 matrix with values ranging from 0 to 8.

In [ ]:
matrx =np.arange(9).reshape(3,3)
print("The required matrix: \n",matrx)

The required matrix: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


Q9. Find indices of non-zero elements from [1,2,0,0,4,0].

In [ ]:
nonz =np.nonzero([1,2,0,0,4,0])
print("Required answer : ",nonz)

Required answer :  (array([0, 1, 4]),)


Q10. Create a 3x3 identity matrix.

In [ ]:
identitymat = np.eye(3)
print("Identity matrix of order 3:\n ",identitymat)

Identity matrix of order 3:
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q11. Create a 3x3x3 array with random values.

In [ ]:
ans = np.random.random([3,3,3])
print("Answer\n",ans)

Answer
 [[[0.84687907 0.60248025 0.72667055]
  [0.19414313 0.22947543 0.2121572 ]
  [0.27463266 0.53986038 0.5155627 ]]

 [[0.01918435 0.17360207 0.51284366]
  [0.03882865 0.94246095 0.72102212]
  [0.68267688 0.19100416 0.73186868]]

 [[0.75387516 0.96066831 0.80203511]
  [0.37616652 0.17382283 0.21887031]
  [0.16998128 0.85908893 0.93813566]]]


Q12. Create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
rm = np.random.random([10,10])
print("Array Created\n",rm)
print("Maximum Value : ",rm.max())
print("Minimum Value : ",rm.min())

Array Created
 [[0.90869628 0.08701569 0.60096492 0.203506   0.80287322 0.51292186
  0.30347704 0.737997   0.53357954 0.14243754]
 [0.47049994 0.69688168 0.72513089 0.88239497 0.13468283 0.64596323
  0.68695432 0.55780769 0.45838716 0.29802912]
 [0.79097201 0.12448369 0.16836145 0.0441974  0.03960462 0.05822307
  0.5004591  0.9903473  0.34864684 0.25018789]
 [0.5208737  0.92459056 0.32526528 0.6986989  0.70144049 0.17543366
  0.46677692 0.645744   0.82874021 0.70064543]
 [0.43101538 0.23092399 0.2023919  0.14420851 0.65287227 0.88255037
  0.20367704 0.72699712 0.44251346 0.61136175]
 [0.00770888 0.63835142 0.15317279 0.55698827 0.93040827 0.80044841
  0.08611908 0.68279559 0.28748113 0.45542729]
 [0.45500688 0.81098299 0.14333941 0.82580358 0.56141668 0.1483682
  0.34516171 0.49356786 0.78302408 0.6949721 ]
 [0.15973111 0.65705172 0.37410083 0.04023046 0.71075673 0.24127803
  0.02526004 0.67700154 0.38662562 0.57977147]
 [0.87211843 0.45964787 0.79855738 0.82440127 0.02402729 0.5681953

Q13. Create a random vector of size 30 and find the mean value.

In [ ]:
rvector = np.random.random(30)
print("The Vector is :\n",rvector)
print("Mean Value : ",rvector.mean())

The Vector is :
 [0.81815643 0.74327586 0.66501756 0.51841631 0.22173348 0.28146676
 0.79770068 0.37408494 0.89306888 0.11491305 0.34206096 0.16499975
 0.43595225 0.52295182 0.29205962 0.91504426 0.49247651 0.80142587
 0.83993696 0.85975059 0.19908194 0.43177622 0.40381664 0.32419303
 0.21178046 0.44217963 0.68971335 0.3600259  0.18438828 0.62210939]
Mean Value :  0.498785247063882


Q14. Create a 2d array with 1 on the border and 0 inside.

In [ ]:
arr2 = np.ones([5,5])
arr2[1:-1,1:-1] = 0
print("The Required 2d array is :\n",arr2)

The Required 2d array is :
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Q15. How to add a border (filled with 0's) around an existing array? 

In [ ]:
#Z =np.ones((5,5))
#Z =np.pad(Z, pad_width=1, mode='constant', constant_values=0)
#print(Z)
existing = np.ones([5,5])
existing[0,:] = 0
existing[-1,:] = 0
existing[:,-1] = 0
existing[:,0] = 0
print("The required array :\n",existing)

The required array :
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


Q16. How to Access/Change specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]


Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [ ]:
arr = np.array([np.arange(1,8),np.arange(8,15)])
print(arr)
print("Element 13 : ",arr[1,5])
print("First Row : ",arr[0,:])
print("Third Column : ",arr[:,2])
print("Printing 2,4,6 from array : ",arr[0,1:6:2])
arr[1,5] = 20
print("New array after replacing 13 by 20 :\n",arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Element 13 :  13
First Row :  [1 2 3 4 5 6 7]
Third Column :  [ 3 10]
Printing 2,4,6 from array :  [2 4 6]
New array after replacing 13 by 20 :
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


Q17. How to Convert a 1D array to a 2D array with 2 rows?

In [ ]:
arr1d = np.random.random(10)
print("1D array : ",arr1d)
arr2d = arr1d.reshape(2,5)
print("Modified 2D array :\n",arr2d)

1D array :  [0.73424313 0.87467924 0.18858815 0.90369651 0.18738045 0.11445494
 0.56862969 0.06212416 0.9338453  0.62272243]
Modified 2D array :
 [[0.73424313 0.87467924 0.18858815 0.90369651 0.18738045]
 [0.11445494 0.56862969 0.06212416 0.9338453  0.62272243]]


Q18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])

Desired Output:

> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
a = np.array([1,2,3])
print("Initial Array :\n",a)
new = np.append(np.repeat(a,3),np.tile(a,3))
print("Output :\n",new)

Initial Array :
 [1 2 3]
Output :
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


Q19. Write a program to show how Numpy taking less memory compared to Python List?

In [ ]:
#memory allocation

l = range(1000)

import sys
print("LIST")
a=10
print("Memory allocated to one element : ",sys.getsizeof(a))   #memory allocated to a
print("Total Memory taken by list : ",sys.getsizeof(a)*len(l))

print("NUMPY ARRAY")
a1 = np.arange(1000)
print("Memory allocated to one element : ",a1.size)
print("Total Memory taken by Numpy array : ",a1.size*a1.itemsize)
#conclusion: numpy takes less memory allocation than list

LIST
Memory allocated to one element :  28
Total Memory taken by list :  28000
NUMPY ARRAY
Memory allocated to one element :  1000
Total Memory taken by Numpy array :  8000


Q20. Write a program to show how Numpy taking less time compared to Python List?

In [ ]:
#Numpy vs List -- speed
import numpy as np
import time
import sys

size = 1000000
l1 = range(size)
l2 = range(size)

n1 = np.arange(size)
n2 = np.arange(size)

#list itemwise sum
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Time taken by Python List : ",(time.time()-start)*1000)

#numpy array itemwise sum
start = time.time()
result1 = n1+n2
print("Time taken by NumPy Array : ",(time.time()-start)*1000)


Time taken by Python List :  163.05971145629883
Time taken by NumPy Array :  2.717256546020508
